#!/usr/bin/env bash
# configure HAproxy

sudo apt install -y haproxy
sudo sed -i '35 a frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n'  /etc/haproxy/haproxy.cfg
sudo sed -i '40 a backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver node1 35.196.10.231:80 check\n\tserver node2 3.235.225.202:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
